name: Build
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Unpack sdist
      run: |
        mkdir -p dist/calver
        tar -xvvf dist/*.tar.gz -C dist/calver/ --strip-components=1
    - name: Install tox
      run: python -m pip install tox
    - name: Test
      run: python -m tox -e py --root dist/calver
