name: Lint
on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install tox
      run: python -m pip install tox
    - name: Lint
      run: python -m tox -e lint
